# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml_schema.proto',
  package='ml_schema',
  syntax='proto2',
  serialized_pb=b'\n\x0fml_schema.proto\x12\tml_schema\"y\n\x10ModelPerformance\x12\x0f\n\x07ModelID\x18\x01 \x01(\t\x12)\n\x07Metrics\x18\x02 \x03(\x0b\x32\x18.ml_schema.MetricSummary\x12)\n\x07\x43utoffs\x18\x03 \x03(\x0b\x32\x18.ml_schema.CutoffMetrics\"s\n\x05Model\x12\n\n\x02ID\x18\x01 \x01(\t\x12,\n\tStructure\x18\x02 \x01(\x0b\x32\x19.ml_schema.ModelStructure\x12\x30\n\x0bPerformance\x18\x03 \x03(\x0b\x32\x1b.ml_schema.ModelPerformance\",\n\rMetricSummary\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x02\"k\n\x0f\x43onfusionMatrix\x12\x14\n\x0cTruePositive\x18\x01 \x01(\x02\x12\x14\n\x0cTrueNegative\x18\x02 \x01(\x02\x12\x15\n\rFalsePositive\x18\x03 \x01(\x02\x12\x15\n\rFalseNegative\x18\x04 \x01(\x02\"I\n\rCutoffMetrics\x12\r\n\x05Value\x18\x01 \x01(\x02\x12)\n\x05Truth\x18\x02 \x01(\x0b\x32\x1a.ml_schema.ConfusionMatrix\"?\n\x0eModelStructure\x12-\n\nComponents\x18\x01 \x03(\x0b\x32\x19.ml_schema.ModelComponent\"\x8f\x01\n\x0eModelComponent\x12\r\n\x05\x43oeff\x18\x01 \x01(\x02\x12\x33\n\x0cRandomForest\x18\x02 \x01(\x0b\x32\x1b.ml_schema.RandomForestDataH\x00\x12\x31\n\x0bLinearCoeff\x18\x03 \x01(\x0b\x32\x1a.ml_schema.LinearCoeffDataH\x00\x42\x06\n\x04\x44\x61ta\"\xc8\x01\n\x0c\x44\x65\x63isionTree\x12\x33\n\x05Nodes\x18\x01 \x03(\x0b\x32$.ml_schema.DecisionTree.DecisionNode\x1a\x82\x01\n\x0c\x44\x65\x63isionNode\x12\x12\n\nAboveChild\x18\x01 \x02(\x05\x12\x12\n\nBelowChild\x18\x02 \x02(\x05\x12\x15\n\rSplitVariable\x18\x03 \x02(\t\x12\x12\n\nSplitValue\x18\x04 \x02(\x01\x12\x10\n\x08LeafNode\x18\x05 \x02(\x08\x12\r\n\x05Label\x18\x06 \x02(\x08\";\n\x10RandomForestData\x12\'\n\x06\x46orest\x18\x01 \x03(\x0b\x32\x17.ml_schema.DecisionTree\"a\n\x0fLinearCoeffData\x12\x11\n\tIntercept\x18\x01 \x01(\x02\x12\r\n\x05\x41lpha\x18\x02 \x01(\x02\x12,\n\x05\x43oeff\x18\x03 \x03(\x0b\x32\x1d.ml_schema.FeatureCoefficient\"4\n\x12\x46\x65\x61tureCoefficient\x12\x0f\n\x07\x46\x65\x61ture\x18\x01 \x01(\t\x12\r\n\x05\x43oeff\x18\x02 \x01(\x02'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODELPERFORMANCE = _descriptor.Descriptor(
  name='ModelPerformance',
  full_name='ml_schema.ModelPerformance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModelID', full_name='ml_schema.ModelPerformance.ModelID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Metrics', full_name='ml_schema.ModelPerformance.Metrics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Cutoffs', full_name='ml_schema.ModelPerformance.Cutoffs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=151,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='ml_schema.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='ml_schema.Model.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Structure', full_name='ml_schema.Model.Structure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Performance', full_name='ml_schema.Model.Performance', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=268,
)


_METRICSUMMARY = _descriptor.Descriptor(
  name='MetricSummary',
  full_name='ml_schema.MetricSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='ml_schema.MetricSummary.Type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='ml_schema.MetricSummary.Value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=314,
)


_CONFUSIONMATRIX = _descriptor.Descriptor(
  name='ConfusionMatrix',
  full_name='ml_schema.ConfusionMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TruePositive', full_name='ml_schema.ConfusionMatrix.TruePositive', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TrueNegative', full_name='ml_schema.ConfusionMatrix.TrueNegative', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FalsePositive', full_name='ml_schema.ConfusionMatrix.FalsePositive', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FalseNegative', full_name='ml_schema.ConfusionMatrix.FalseNegative', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=423,
)


_CUTOFFMETRICS = _descriptor.Descriptor(
  name='CutoffMetrics',
  full_name='ml_schema.CutoffMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='ml_schema.CutoffMetrics.Value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Truth', full_name='ml_schema.CutoffMetrics.Truth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=498,
)


_MODELSTRUCTURE = _descriptor.Descriptor(
  name='ModelStructure',
  full_name='ml_schema.ModelStructure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Components', full_name='ml_schema.ModelStructure.Components', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=563,
)


_MODELCOMPONENT = _descriptor.Descriptor(
  name='ModelComponent',
  full_name='ml_schema.ModelComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Coeff', full_name='ml_schema.ModelComponent.Coeff', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RandomForest', full_name='ml_schema.ModelComponent.RandomForest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LinearCoeff', full_name='ml_schema.ModelComponent.LinearCoeff', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Data', full_name='ml_schema.ModelComponent.Data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=566,
  serialized_end=709,
)


_DECISIONTREE_DECISIONNODE = _descriptor.Descriptor(
  name='DecisionNode',
  full_name='ml_schema.DecisionTree.DecisionNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AboveChild', full_name='ml_schema.DecisionTree.DecisionNode.AboveChild', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BelowChild', full_name='ml_schema.DecisionTree.DecisionNode.BelowChild', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SplitVariable', full_name='ml_schema.DecisionTree.DecisionNode.SplitVariable', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SplitValue', full_name='ml_schema.DecisionTree.DecisionNode.SplitValue', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LeafNode', full_name='ml_schema.DecisionTree.DecisionNode.LeafNode', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Label', full_name='ml_schema.DecisionTree.DecisionNode.Label', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=782,
  serialized_end=912,
)

_DECISIONTREE = _descriptor.Descriptor(
  name='DecisionTree',
  full_name='ml_schema.DecisionTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Nodes', full_name='ml_schema.DecisionTree.Nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DECISIONTREE_DECISIONNODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=912,
)


_RANDOMFORESTDATA = _descriptor.Descriptor(
  name='RandomForestData',
  full_name='ml_schema.RandomForestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Forest', full_name='ml_schema.RandomForestData.Forest', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=914,
  serialized_end=973,
)


_LINEARCOEFFDATA = _descriptor.Descriptor(
  name='LinearCoeffData',
  full_name='ml_schema.LinearCoeffData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Intercept', full_name='ml_schema.LinearCoeffData.Intercept', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Alpha', full_name='ml_schema.LinearCoeffData.Alpha', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Coeff', full_name='ml_schema.LinearCoeffData.Coeff', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=975,
  serialized_end=1072,
)


_FEATURECOEFFICIENT = _descriptor.Descriptor(
  name='FeatureCoefficient',
  full_name='ml_schema.FeatureCoefficient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Feature', full_name='ml_schema.FeatureCoefficient.Feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Coeff', full_name='ml_schema.FeatureCoefficient.Coeff', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1074,
  serialized_end=1126,
)

_MODELPERFORMANCE.fields_by_name['Metrics'].message_type = _METRICSUMMARY
_MODELPERFORMANCE.fields_by_name['Cutoffs'].message_type = _CUTOFFMETRICS
_MODEL.fields_by_name['Structure'].message_type = _MODELSTRUCTURE
_MODEL.fields_by_name['Performance'].message_type = _MODELPERFORMANCE
_CUTOFFMETRICS.fields_by_name['Truth'].message_type = _CONFUSIONMATRIX
_MODELSTRUCTURE.fields_by_name['Components'].message_type = _MODELCOMPONENT
_MODELCOMPONENT.fields_by_name['RandomForest'].message_type = _RANDOMFORESTDATA
_MODELCOMPONENT.fields_by_name['LinearCoeff'].message_type = _LINEARCOEFFDATA
_MODELCOMPONENT.oneofs_by_name['Data'].fields.append(
  _MODELCOMPONENT.fields_by_name['RandomForest'])
_MODELCOMPONENT.fields_by_name['RandomForest'].containing_oneof = _MODELCOMPONENT.oneofs_by_name['Data']
_MODELCOMPONENT.oneofs_by_name['Data'].fields.append(
  _MODELCOMPONENT.fields_by_name['LinearCoeff'])
_MODELCOMPONENT.fields_by_name['LinearCoeff'].containing_oneof = _MODELCOMPONENT.oneofs_by_name['Data']
_DECISIONTREE_DECISIONNODE.containing_type = _DECISIONTREE
_DECISIONTREE.fields_by_name['Nodes'].message_type = _DECISIONTREE_DECISIONNODE
_RANDOMFORESTDATA.fields_by_name['Forest'].message_type = _DECISIONTREE
_LINEARCOEFFDATA.fields_by_name['Coeff'].message_type = _FEATURECOEFFICIENT
DESCRIPTOR.message_types_by_name['ModelPerformance'] = _MODELPERFORMANCE
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['MetricSummary'] = _METRICSUMMARY
DESCRIPTOR.message_types_by_name['ConfusionMatrix'] = _CONFUSIONMATRIX
DESCRIPTOR.message_types_by_name['CutoffMetrics'] = _CUTOFFMETRICS
DESCRIPTOR.message_types_by_name['ModelStructure'] = _MODELSTRUCTURE
DESCRIPTOR.message_types_by_name['ModelComponent'] = _MODELCOMPONENT
DESCRIPTOR.message_types_by_name['DecisionTree'] = _DECISIONTREE
DESCRIPTOR.message_types_by_name['RandomForestData'] = _RANDOMFORESTDATA
DESCRIPTOR.message_types_by_name['LinearCoeffData'] = _LINEARCOEFFDATA
DESCRIPTOR.message_types_by_name['FeatureCoefficient'] = _FEATURECOEFFICIENT

ModelPerformance = _reflection.GeneratedProtocolMessageType('ModelPerformance', (_message.Message,), dict(
  DESCRIPTOR = _MODELPERFORMANCE,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.ModelPerformance)
  ))
_sym_db.RegisterMessage(ModelPerformance)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.Model)
  ))
_sym_db.RegisterMessage(Model)

MetricSummary = _reflection.GeneratedProtocolMessageType('MetricSummary', (_message.Message,), dict(
  DESCRIPTOR = _METRICSUMMARY,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.MetricSummary)
  ))
_sym_db.RegisterMessage(MetricSummary)

ConfusionMatrix = _reflection.GeneratedProtocolMessageType('ConfusionMatrix', (_message.Message,), dict(
  DESCRIPTOR = _CONFUSIONMATRIX,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.ConfusionMatrix)
  ))
_sym_db.RegisterMessage(ConfusionMatrix)

CutoffMetrics = _reflection.GeneratedProtocolMessageType('CutoffMetrics', (_message.Message,), dict(
  DESCRIPTOR = _CUTOFFMETRICS,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.CutoffMetrics)
  ))
_sym_db.RegisterMessage(CutoffMetrics)

ModelStructure = _reflection.GeneratedProtocolMessageType('ModelStructure', (_message.Message,), dict(
  DESCRIPTOR = _MODELSTRUCTURE,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.ModelStructure)
  ))
_sym_db.RegisterMessage(ModelStructure)

ModelComponent = _reflection.GeneratedProtocolMessageType('ModelComponent', (_message.Message,), dict(
  DESCRIPTOR = _MODELCOMPONENT,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.ModelComponent)
  ))
_sym_db.RegisterMessage(ModelComponent)

DecisionTree = _reflection.GeneratedProtocolMessageType('DecisionTree', (_message.Message,), dict(

  DecisionNode = _reflection.GeneratedProtocolMessageType('DecisionNode', (_message.Message,), dict(
    DESCRIPTOR = _DECISIONTREE_DECISIONNODE,
    __module__ = 'ml_schema_pb2'
    # @@protoc_insertion_point(class_scope:ml_schema.DecisionTree.DecisionNode)
    ))
  ,
  DESCRIPTOR = _DECISIONTREE,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.DecisionTree)
  ))
_sym_db.RegisterMessage(DecisionTree)
_sym_db.RegisterMessage(DecisionTree.DecisionNode)

RandomForestData = _reflection.GeneratedProtocolMessageType('RandomForestData', (_message.Message,), dict(
  DESCRIPTOR = _RANDOMFORESTDATA,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.RandomForestData)
  ))
_sym_db.RegisterMessage(RandomForestData)

LinearCoeffData = _reflection.GeneratedProtocolMessageType('LinearCoeffData', (_message.Message,), dict(
  DESCRIPTOR = _LINEARCOEFFDATA,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.LinearCoeffData)
  ))
_sym_db.RegisterMessage(LinearCoeffData)

FeatureCoefficient = _reflection.GeneratedProtocolMessageType('FeatureCoefficient', (_message.Message,), dict(
  DESCRIPTOR = _FEATURECOEFFICIENT,
  __module__ = 'ml_schema_pb2'
  # @@protoc_insertion_point(class_scope:ml_schema.FeatureCoefficient)
  ))
_sym_db.RegisterMessage(FeatureCoefficient)


# @@protoc_insertion_point(module_scope)
